### ISSUE TITLE
Can you lower go.mod dependency value  from 1.23 to 1.22?

### ISSUE THREAD

**Issue by nlacey** [gomlx/gomlx#100]
Within your go.mod file, the min go value is 1.23 (probably because that's what version you are running on your machine)

Go is currently supporting both 1.22 and 1.23.

I believe, generally you want to make your go.mod version at least support the 2 supported versions of go. (if allowed by all of your sub-dependencies)

Thanks

**Comment by janpfeifer** [comment]
hey Nathan,

I apologize, but actually, I started adopting iterators in some places, which I believe started in Go 1.23 😞 Maybe it was a mistake, and I should have waited longer. As you mentioned I should be supporting the last 2 versions.

But even if not using iterators, because of the GoMLX dependency on CGO -- I wish we didn't need it, but... -- when Go 1.24 comes out, I plan to use the new (and better) [`runtime.AddCleanup`](https://tip.golang.org/doc/go1.24#weak) (replacing the `runtime.SetFinalizer`, and improving GC of C++ owned stuff I hope, the latency in GC hurts in some cases)  and the [better annotation for the CGO](https://tip.golang.org/doc/go1.24#cgo), that will hopefully shave off some time when calling C/C++, which will help significantly in some use cases (smaller models).

While I agree, the project should maintain the last 2 versions ... being mostly a one-person project (for now) ... I don't have the bandwidth to maintain that.

But I'll try to postpone the 1.24 modifications at least for a couple of months, and it is shown to be stable.

**Comment by nlacey** [comment]
great work with all of this!
I'm totally not trying to get in the way of your progress! (and don't let anyone else that isn't contributing do that either )  ;-)

I just know a bunch of new projects, just take go's default!
You have valid reasons! which is all I'm looking to validate.
