### ISSUE TITLE
GoMLX+XLA C library does not compile on MacOS

### ISSUE THREAD

**Issue by tdegris** [gomlx/gomlx#23]
The following error is reported:
```
gomlx/status.cpp:20:10: fatal error: 'gperftools/malloc_extension.h' file not found
#include "gperftools/malloc_extension.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Does Bazel need to find it on the system (in which case it is installed by default by homebrew `/opt/homebrew/include/google/`) or can Bazel download it from https://github.com/gperftools/gperftools/releases ? Thank you.

**Comment by janpfeifer** [comment]
hi @tdegris , apologies, I don't have access to a Mac, so I never tried to compile it there.

Yes, this is part of the  libgoogle-perftools-dev dependency, that I point out -- which in linux is an `apt-get install` (or some variation) away -- maybe it's as easy with homebrew ? Notice there are a few of other dependencies: "libunwind8", "liblzma5" and "hdf5-tools" (it uses/executeds the command line tool "hddump" to extract weights from .h5 files in some examples).

I hadn't realized that I could indeed add the dependency to gperftools in Bazel, and even link it statically. I should try it next.

**Comment by tdegris** [comment]
Thank you for your response.

See https://github.com/gomlx/gomlx/pull/24

**Comment by janpfeifer** [comment]
Thank you for the PR, I already merged it!

While testing, I found a caveat: it includes the `libtcmalloc.so` in the `gomlx_xla.tar.gz` file, which is an issue because it may overwrite  the library that may already be there -- imagine is other software packages also did that ?!

What would you think of the following alternatives:

1. Statically link libtcmalloc.a: so libtcmalloc.so is not strictly needed.
2. Create a subdirectory `lib/gomlx/` and put the GoMLX tcmalloc.so version there.

Would that work in Mac / for you ? I could do also do both, 1+2.

**Comment by janpfeifer** [comment]
<venting>Ugh, building C++ is nightmarish and only gets worse over the years ... another reason why I moved most of my development to Go, whenever I can.</venting>

I'm not able to statically link `tcmalloc` to `libgomlx_xla.so` for some inscrutable reason. Creating a `cc_import` rule fails with some obscure:

```
/usr/bin/ld: bazel-out/k8-opt/bin/external/gperftools/libtcmalloc.a(libtcmalloc_la-tcmalloc.o): relocation R_X86_64_PC32 against symbol `_ZN8tcmalloc6Static7inited_E' can not be used when making a shared object; recompile with -fPIC
```

But still, gomlx_xla.tar.gz shouldn't include `libtcmalloc` in the `/lib` directory, since it may override a `libtcmalloc` that is already there -- (someone installing gomlx shouldn't have such a side effect). 

So instead I'm including `libtcmalloc` files under `/lib/gomlx/`, so it won't risk conflicts ... at the cost of the extra step for the user having to include that directory in their "LD_LIBRARY_PATH" variable, or simply copying the libtcmalloc files somewhere they find appropriate (typically /usr/local/lib).

Any thoughts ?



   I've been doing C++ since the early 90s (when the first versions started), and it's building just get worse :)

**Comment by tdegris** [comment]
Yes, I also tried to build tcmalloc statically and came to the conclusion that MacOS would just not allow it.

One issue I had with installing gpertools is that all the headers where in include/google instead of include/gperftools. Installing a local version of gperftools seemed like a good option at the time but perhaps it was not.

Anyway, your solution works for me.

**Comment by janpfeifer** [comment]
Nice, thanks!

Then I'll leave it at that. I also added a comment on the README.md for others looking for a MacOS build.
